<?php
return

array (
  'head' => 
  array (
    0 => '<!DOCTYPE html>',
    1 => '<html lang="en-US" dir="ltr">',
    2 => '<head>',
    3 => '<meta charset="utf-8" />',
    4 => '',
    5 => '<!-- Compatibility Settings',
    6 => '============================================= -->',
    7 => '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />',
    8 => '<meta http-equiv="X-UA-Compatible" content="IE=edge">',
    9 => '<!-- Compatibility Settings end -->',
    10 => '<!-- Web Fonts',
    11 => '============================================= -->',
    12 => '<!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700,800" rel="stylesheet"> -->',
    13 => '<!-- Web Fonts  end -->',
    14 => '<!-- Core & Theme CSS',
    15 => '============================================= -->',
    16 => '<!-- Basic  -->',
    17 => '<link rel="stylesheet" href="../assets/css/bootstrap.min.css?ver=4.2.1" media="all"/>',
    18 => '<link rel="stylesheet" href="../assets/css/video.min.css?ver=7.4.1" media="all"/>',
    19 => '<!-- Icons  -->',
    20 => '<link rel="stylesheet" href="../assets/fonts/fontawesome/css/all.min.css?ver=5.7.0">',
    21 => '<link rel="stylesheet" href="../assets/fonts/fontawesome/css/v4-shims.min.css?ver=5.7.0">',
    22 => '<!-- Theme  -->',
    23 => '<link rel="stylesheet" href=../css/uix-kit.min.css?ver=qXJ1d1suw95dRqLHFWpI"/>',
    24 => '<!--[if lt IE 10]>',
    25 => '<link rel="stylesheet" href="../assets/css/IE.css?ver=qXJ1d1suw95dRqLHFWpI" />',
    26 => '<![endif]-->',
    27 => '<!-- Core & Theme CSS  end -->',
    28 => '<!-- Vendor',
    29 => '============================================= -->',
    30 => '<script src="../assets/js/wp-jquery/jquery.min.js?ver=3.3.1"></script>',
    31 => '<script src="../assets/js/wp-jquery/jquery.migrate.min.js?ver=1.4.1"></script>',
    32 => '<script src="../assets/js/min/modernizr.min.js?ver=3.5.0"></script>',
    33 => '<!-- Vendor  end -->',
    34 => '<!-- Break free from CSS prefix hell!',
    35 => '============================================= -->',
    36 => '<script src="../assets/js/min/prefixfree.min.js?ver=1.0.7"></script>',
    37 => '<!-- SEO',
    38 => '============================================= -->',
    39 => '<meta name="description" content="A free web kits for fast web design and development, compatible with Bootstrap v4.">',
    40 => '<meta name="generator" content="Uix Kit" />',
    41 => '<meta name="author" content="UIUX Lab">',
    42 => '<!-- SEO  end -->',
    43 => '<!-- Favicons',
    44 => '============================================= -->',
    45 => '<link rel="icon" href="../assets/images/favicon/favicon-32x32.png" type="image/x-icon">',
    46 => '<link rel="shortcut icon" href="../assets/images/favicon/favicon-32x32.png" sizes="32x32">',
    47 => '<link rel="apple-touch-icon" href="../assets/images/favicon/apple-touch-icon-57x57.png">',
    48 => '<link rel="apple-touch-icon" sizes="72x72" href="../assets/images/favicon/apple-touch-icon-72x72.png">',
    49 => '<link rel="apple-touch-icon" sizes="114x114" href="../assets/images/favicon/apple-touch-icon-114x114.png">',
    50 => '<!-- Favicons  end -->',
    51 => '</head>',
  ),
  'content' => 
  array (
    0 => '<body class="page">',
    1 => '<!-- Loader',
    2 => '============================================= -->',
    3 => '<div class="uix-loader">',
    4 => '<!--[if lt IE 10]>',
    5 => '<span>Loading...</span>',
    6 => '<![endif]-->',
    7 => '<svg class="uix-loader__spinner is-hide-IE" viewBox="0 0 52 52">',
    8 => '<path d="M25.251,6.461c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615V6.461z"></path>',
    9 => '</svg>',
    10 => '</div>',
    11 => '<div class="uix-loader-progress" data-txt="{progress}%"><span>0%</span></div>',
    12 => '<div class="uix-loader-progress__line"></div>',
    13 => '<!-- .uix-loader end -->',
    14 => '<!-- Mobile Menu Toggle Trigger',
    15 => '============================================= -->',
    16 => '<div class="uix-menu-mobile__toggle">',
    17 => '<span></span>',
    18 => '<span></span>',
    19 => '<span></span>',
    20 => '</div>',
    21 => '<div class="uix-menu-mobile__mask"></div>',
    22 => '<!-- .uix-menu-mobile__toggle end -->',
    23 => '<div class="uix-wrapper">',
    24 => '<!-- Header Area',
    25 => '============================================= -->',
    26 => '<div class="uix-header__placeholder js-uix-header__placeholder-autoheight"></div>',
    27 => '<!-- Footer',
    28 => '============================================= -->',
    29 => '</div>',
    30 => '<!-- .uix-wrapper end -->',
  ),
  'nav' => 
  array (
    0 => '<header class="uix-header__container">',
    1 => '<div class="uix-header">',
    2 => '<div class="container">',
    3 => '<div class="uix-brand">',
    4 => '<a href="index.html"><img src="../assets/images/logo.png" alt="Uix Kit"></a>',
    5 => '</div>',
    6 => '<!-- .uix-brand end -->',
    7 => '<!-- Navigation Start-->',
    8 => '<nav class="uix-menu__container">',
    9 => '<div class="uix-menu__inner">',
    10 => '<span class="uix-brand--mobile"><img src="../assets/images/logo-colorful.png" alt="Uix Kit"></span>',
    11 => '<ul class="uix-menu">',
    12 => '<li class="multi-column current-menu-item is-active"><a href="index.html">Components</a>',
    13 => '<ul class="sub-menu">',
    14 => '<li>',
    15 => '<span class="multi-column-title">Web Elements (Basic)</span>',
    16 => '<ul class="sub-menu">',
    17 => '<li><a href="helper-classes.html">Helper Classes</a></li>',
    18 => '<li><a href="uix-grid.html">Uix Grid</a></li>',
    19 => '<li><a href="bootstrap-grid.html">Bootstrap Grid</a></li>',
    20 => '<li><a href="blended-grid-layout.html">Blended Grid</a></li>',
    21 => '<li><a href="gallery-grid-layout.html">Gallery Grid</a></li>',
    22 => '<li><a href="spacing.html">Spacing</a></li>',
    23 => '<li><a href="material-container.html">Material Container</a></li>',
    24 => '<li><a href="striking.html">Striking</a></li>',
    25 => '<li><a href="button.html">Buttons</a></li>',
    26 => '<li><a href="overlay.html">Overlay</a></li>',
    27 => '<li><a href="video.html">Video</a></li>',
    28 => '<li><a href="video-background.html">Video BG</a></li>',
    29 => '<li><a href="heading.html">Heading</a></li>',
    30 => '<li><a href="dividing-line.html">Dividing Line</a></li>',
    31 => '<li><a href="images.html">Images</a></li>',
    32 => '<li><a href="responsive-images.html">Responsive Images</a></li>',
    33 => '<li><a href="background-interaction.html">Background</a></li>',
    34 => '<li><a href="parallax.html">Parallax</a></li>',
    35 => '<li><a href="parallax2.html">Parallax 2</a></li>',
    36 => '<li><a href="vertical-centering.html">Vertical Centering</a></li>',
    37 => '<li><a href="equal-width-columns.html">Equal-width Columns</a></li>',
    38 => '<li><a href="equal-height-columns.html">Equal-height Columns</a></li>',
    39 => '<li><a href="align-wide-and-full-element.html">Align Wide/Full Element</a><span class="uix-bubble">new</span></li>',
    40 => '</ul>',
    41 => '<!-- .sub-menu  end -->',
    42 => '</li>',
    43 => '<li>',
    44 => '<span class="multi-column-title">Web Elements (Part 1)</span>',
    45 => '<ul class="sub-menu">',
    46 => '<li><a href="navs.html">Navs</a></li>',
    47 => '<li><a href="breadcrumbs.html">Breadcrumbs</a></li>',
    48 => '<li><a href="lightbox.html">Lightbox</a></li>',
    49 => '<li><a href="modal-dialog.html">Modal Dialog</a></li>',
    50 => '<li><a href="modal-dialog-auto.html">Modal Dialog Auto-open</a></li>',
    51 => '<li><a href="social-meida-icons.html">Social Media Icons</a></li>',
    52 => '<li><a href="form.html">Form Elements</a></li>',
    53 => '<li><a href="form2.html">Form Elements 2</a></li>',
    54 => '<li><a href="form-layout.html">Form Layout</a></li>',
    55 => '<li><a href="form-progress.html">Form Progress</a></li>',
    56 => '<li><a href="counter.html">Counter</a></li>',
    57 => '<li><a href="progress-bar.html">Progress Bar</a></li>',
    58 => '<li><a href="progress-line.html">Progress Line</a></li>',
    59 => '<li><a href="vertical-text.html">Vertical Text</a></li>',
    60 => '<li><a href="circle-text.html">Circle Text</a></li>',
    61 => '<li><a href="coach-mark.html">Coach Mark</a></li>',
    62 => '<li><a href="separator-of-rule-with-text.html">Separator of Rule With Text</a></li>',
    63 => '<li><a href="wave-background.html">Wave Background</a></li>',
    64 => '<li><a href="shape-animation.html">Shape Animation</a></li>',
    65 => '<li><a href="image-animation.html">Image Animation</a></li>',
    66 => '<li><a href="svg-map.html">SVG Map</a></li>',
    67 => '<li><a href="floating-side-element.html">Floating Side Element</a></li>',
    68 => '<li><a href="infinite-scrolling-element.html">Infinite Scrolling Element</a><span class="uix-bubble">new</span></li>',
    69 => '</ul>',
    70 => '<!-- .sub-menu  end -->',
    71 => '</li>',
    72 => '<li>',
    73 => '<span class="multi-column-title">Web Elements (Part 2)</span>',
    74 => '<ul class="sub-menu">',
    75 => '<li><a href="tooltip.html">Tooltip</a></li>',
    76 => '<li><a href="ribbon.html">Ribbon</a></li>',
    77 => '<li><a href="footer-templates.html">Footer Templates</a></li>',
    78 => '<li><a href="login-templates.html">Login Templates</a><span class="uix-bubble">new</span></li>',
    79 => '<li><a href="pagination.html">Pagination</a></li>',
    80 => '<li><a href="badges.html">Badges</a></li>',
    81 => '<li><a href="mouse-animation-scroll.html">Mouse Animation Scroll</a></li>',
    82 => '<li><a href="periodical-scroll.html">Periodical Scroll</a></li>',
    83 => '<li><a href="image-shapes.html">Image Shapes</a></li>',
    84 => '<li><a href="rotating-elements.html">Rotating Elements</a></li>',
    85 => '<li><a href="dotted-line.html">Dotted Line</a></li>',
    86 => '<li><a href="flexslider.html">Flexslider<small style="font-size: 10px;background: #51B801; color:#fff; border-radius: 5px;padding: 2px 3px;display: inline-block;margin-left: 3px;">Third-party plugin</small></a></li>',
    87 => '<li><a href="swiper.html">Swiper<small style="font-size: 10px;background: #51B801; color:#fff; border-radius: 5px;padding: 2px 3px;display: inline-block;margin-left: 3px;">Third-party plugin</small></a></li>',
    88 => '<li><a href="advanced-slider.html">Advanced Slider (Basic)</a></li>',
    89 => '<li><a href="advanced-slider-brightness.html">Advanced Slider Brightness</a></li>',
    90 => '<li><a href="advanced-slider-liquid.html">Advanced Slider Liquid</a></li>',
    91 => '<li><a href="advanced-slider-liquid2.html">Advanced Slider Liquid 2</a></li>',
    92 => '<li><a href="advanced-slider-liquid3.html">Advanced Slider Liquid 3</a></li>',
    93 => '<li><a href="advanced-slider-parallax.html">Advanced Slider Parallax</a></li>',
    94 => '<li><a href="hybrid-content-slider.html">Hybrid Content Slider</a><span class="uix-bubble">new</span></li>',
    95 => '<li><a href="svg-mask-slider.html">SVG Mask Slider</a><span class="uix-bubble">new</span></li>',
    96 => '<li><a href="3D-explosive-particle-slider.html">3D Explosive Particle Slider</a></li>',
    97 => '<li><a href="3D-shatter-slider.html">3D Shatter Slider</a></li>',
    98 => '<li><a href="3D-liquid-scrollspy-slider.html">3D Liquid Scrollspy Slider</a><span class="uix-bubble">new</span></li>',
    99 => '</ul>',
    100 => '<!-- .sub-menu  end -->',
    101 => '</li>',
    102 => '<li>',
    103 => '<span class="multi-column-title">Contents (Part 1)</span>',
    104 => '<ul class="sub-menu">',
    105 => '<li><a href="content-placeholder-animated.html">Content Placeholder Animated</a></li>',
    106 => '<li><a href="list-posts.html">Posts List</a></li>',
    107 => '<li><a href="fullwidth-column-to-edge.html">Full Width Column to Edge</a><span class="uix-bubble">new</span></li>',
    108 => '<li><a href="list-side-by-side.html">Side by Side List</a></li>',
    109 => '<li><a href="list-side-by-side-img.html">Side by Side List With Photo</a></li>',
    110 => '<li><a href="list-bulleted.html">Bulleted List</a></li>',
    111 => '<li><a href="list-brands.html">Brands List</a></li>',
    112 => '<li><a href="list-maintain-aspect-ratio.html">Maintain Aspect Ratio List</a></li>',
    113 => '<li><a href="single-post.html">Single Post</a></li>',
    114 => '<li><a href="sidebar.html">Sidebar</a></li>',
    115 => '<li><a href="contact.html">Contact Form With Map</a></li>',
    116 => '<li><a href="features.html">Features</a></li>',
    117 => '<li><a href="pricing.html">Pricing</a></li>',
    118 => '<li><a href="testimonials.html">Testimonials</a></li>',
    119 => '<li><a href="tabs.html">Tabs</a></li>',
    120 => '<li><a href="accordion.html">Accordion</a></li>',
    121 => '<li><a href="accordion-img.html">Accordion Background Images</a></li>',
    122 => '<li><a href="gallery.html">Gallery Normal</a></li>',
    123 => '<li><a href="gallery-filter.html">Gallery Filterable</a></li>',
    124 => '<li><a href="gallery-masonry.html">Gallery Masonry</a></li>',
    125 => '<li><a href="gallery-masonry-ajax.html">Gallery Masonry With Ajax</a><span class="uix-bubble">new</span></li>',
    126 => '</ul>',
    127 => '<!-- .sub-menu  end -->',
    128 => '</li>',
    129 => '<li>',
    130 => '<span class="multi-column-title">Contents (Part 2)</span>',
    131 => '<ul class="sub-menu">',
    132 => '<li><a href="card.html">Cards</a></li>',
    133 => '<li><a href="table-series.html">Table</a></li>',
    134 => '<li><a href="table-sorter.html">Table Sorter</a></li>',
    135 => '<li><a href="timeline.html">Timeline</a></li>',
    136 => '<li><a href="multi-items-carousel.html">Multiple Items Carousel</a></li>',
    137 => '<li><a href="team-fullwidth.html">Team Fullwidth</a></li>',
    138 => '<li><a href="team-grid.html">Team Grid</a></li>',
    139 => '<li><a href="team-focus.html">Team Focus</a></li>',
    140 => '<li><a href="circle-layout.html">Circle Layout</a></li>',
    141 => '<li><a href="3D-carousel.html">3D Carousel</a></li>',
    142 => '<li><a href="3D-gallery.html">3D Gallery (threejs)</a></li>',
    143 => '<li><a href="cascading-dropdown-list.html">Cascading DropDown List</a><span class="uix-bubble">new</span></li>',
    144 => '</ul>',
    145 => '<!-- .sub-menu  end -->',
    146 => '</li>',
    147 => '<li>',
    148 => '<span class="multi-column-title">Interaction (Part 1)</span>',
    149 => '<ul class="sub-menu">',
    150 => '<li><a href="sticky-elements.html">Sticky Elements</a></li>',
    151 => '<li><a href="scroll-reveal.html">Scroll Reveal</a></li>',
    152 => '<li><a href="scrollspy-animate.html">Scrollspy Animate</a><span class="uix-bubble">new</span></li>',
    153 => '<li><a href="skew-on-scroll.html">Skew on Scroll</a><span class="uix-bubble">new</span></li>',
    154 => '<li><a href="text-effect.html">Text Effect</a><span class="uix-bubble">new</span></li>',
    155 => '<li><a href="smooth-scrolling-page.html">Smooth Scrolling Page</a></li>',
    156 => '<li><a href="list-posts-with-ajax.html">Ajax Load Posts</a></li>',
    157 => '<li><a href="list-posts-with-ajax2.html">Ajax Load Posts 2</a></li>',
    158 => '<li><a href="list-posts-with-ajax-infinitescroll.html">Infinite Scroll Posts</a></li>',
    159 => '<li><a href="show-more-less.html">Show More Less</a></li>',
    160 => '<li><a href="mousewheel-interaction.html">Mousewheel Interaction</a></li>',
    161 => '<li><a href="hover-delay-interaction.html">Hover Delay Interaction</a></li>',
    162 => '<li><a href="one-page.html">Full Page/One Page</a></li>',
    163 => '<li><a href="one-page2.html">Full Page/One Page 2</a></li>',
    164 => '<li><a href="ajax-page-loader.html">Ajax Page Loader</a></li>',
    165 => '<li><a href="ajax-push-content.html">Ajax Push Content</a></li>',
    166 => '<li><a href="3D-background.html">3D Background</a></li>',
    167 => '<li><a href="3D-background-three.html">3D Background 1 (threejs)</a></li>',
    168 => '<li><a href="3D-background-three2.html">3D Background 2 (threejs)</a></li>',
    169 => '<li><a href="3D-background-three3.html">3D Background 3 (threejs)</a></li>',
    170 => '<li><a href="3D-simulate-html-layout.html">Simulate HTML Layout (threejs)</a></li>',
    171 => '</ul>',
    172 => '<!-- .sub-menu  end -->',
    173 => '</li>',
    174 => '<li>',
    175 => '<span class="multi-column-title">Interaction (Part 2)</span>',
    176 => '<ul class="sub-menu">',
    177 => '<li><a href="3D-pages.html">3D Pages</a></li>',
    178 => '<li><a href="3D-particle-effect.html">3D Particle Effect</a></li>',
    179 => '<li><a href="3D-sphere-three.html">3D Sphere Rotation</a></li>',
    180 => '<li><a href="3D-obj-anim-interaction.html">3D Object Anim Interaction</a></li>',
    181 => '<li><a href="3D-image-transition.html">3D Image Transition (threejs)</a></li>',
    182 => '<li><a href="3D-mouse-interaction.html">3D Mouse Interaction (threejs)</a></li>',
    183 => '<li><a href="3D-mouse-interaction2.html">3D Mouse Interaction2 (threejs)</a></li>',
    184 => '<li><a href="3D-model.html">3D Model</a></li>',
    185 => '<li><a href="3D-filmic-effects.html">3D Filmic Effects</a><span class="uix-bubble">new</span></li>',
    186 => '</ul>',
    187 => '<!-- .sub-menu  end -->',
    188 => '</li>',
    189 => '</ul>',
    190 => '</li>',
    191 => '<li><a href="#">Menu</a>',
    192 => '<ul class="sub-menu">',
    193 => '<li><a href="mega-menu.html">Mega Menu</a></li>',
    194 => '<li><a href="mega-menu-rtl.html">Mega Menu(RTL)</a></li>',
    195 => '<li><a href="dropdown-menu.html">Dropdown Menu</a></li>',
    196 => '<li><a href="dropdown-menu2.html">Dropdown Menu 2(Multi-level)</a></li>',
    197 => '<li><a href="vertical-menu.html" target="_blank">Vertical Menu</a></li>',
    198 => '<li><a href="lava-lamp-style-menu.html">Lava-Lamp Style Menu</a><span class="uix-bubble">new</span></li>',
    199 => '</ul>',
    200 => '<!-- .sub-menu  end -->',
    201 => '</li>',
    202 => '<li><a href="typography.html">Typography</a>',
    203 => '<ul class="sub-menu">',
    204 => '<li><a href="typography.html">LTR</a></li>',
    205 => '<li><a href="typography-rtl.html">RTL</a></li>',
    206 => '<li><a href="typography-cn.html">中文</a></li>',
    207 => '</ul>',
    208 => '</li>',
    209 => '<li><a href="sample-page-1.html">Sample Pages</a>',
    210 => '<ul class="sub-menu">',
    211 => '<li><a href="sample-page-1.html">Sample Page 1</a></li>',
    212 => '<li><a href="sample-page-2.html">Sample Page 2</a></li>',
    213 => '</ul>',
    214 => '</li>',
    215 => '</ul>',
    216 => '<div class="uix-menu__right-box">',
    217 => '<a class="uix-social-btn uix-social-btn--small uix-social-btn--circle uix-social-btn--thin uix-social-btn--white" title="Follow us on Twitter" href="https://twitter.com/uiux_lab" target="_blank">',
    218 => '<i class="fa fa-twitter"></i>',
    219 => '</a>',
    220 => '<a class="uix-social-btn uix-social-btn--small uix-social-btn--circle uix-social-btn--thin uix-social-btn--white" title="Follow us on Facebook" href="https://www.facebook.com/uiuxlabhome" target="_blank">',
    221 => '<i class="fa fa-facebook"></i>',
    222 => '</a>',
    223 => '<a class="uix-social-btn uix-social-btn--small uix-social-btn--circle uix-social-btn--thin uix-social-btn--white" title="Fork on Github" href="https://github.com/xizon/uix-kit" target="_blank">',
    224 => '<i class="fa fa-github"></i>',
    225 => '</a>',
    226 => '</div>',
    227 => '</div><!-- /.uix-menu__inner -->',
    228 => '</nav>',
    229 => '<!-- .uix-menu__container end -->',
    230 => '</div>',
    231 => '<!-- .container end -->',
    232 => '<div class="uix-clearfix"></div>',
    233 => '</div>',
    234 => '</header>',
  ),
  'main' => 
  array (
    0 => '<main id="uix-maincontent">',
    1 => '<!-- Content',
    2 => '====================================================== -->',
    3 => '<section class="uix-spacing--s uix-spacing--no-bottom">',
    4 => '<div class="container">',
    5 => '<div class="row">',
    6 => '<div class="col-12">',
    7 => '<h3>Common Helper Classes</h3>',
    8 => '<p>Helper classes can help remove repetition by creating a set of abstract classes that can be used over and over on HTML elements. </p>',
    9 => '<hr>',
    10 => '</div>',
    11 => '</div>',
    12 => '<!-- .row end -->',
    13 => '</div>',
    14 => '<!-- .container end -->',
    15 => '</section>',
    16 => '<!-- Content',
    17 => '====================================================== -->',
    18 => '<section class="uix-spacing--s">',
    19 => '<div class="container uix-list uix-list--normal uix-table uix-table--bordered">',
    20 => '<div class="row">',
    21 => '<div class="col-12">',
    22 => '<div class="table-responsive-md">',
    23 => '<div class="uix-table uix-table--bordered">',
    24 => '<table>',
    25 => '<thead>',
    26 => '<tr>',
    27 => '<th>Typography</th>',
    28 => '<th>Color</th>',
    29 => '<th>Display property</th>',
    30 => '</tr>',
    31 => '</thead>',
    32 => '<tbody>',
    33 => '<tr>',
    34 => '<td>',
    35 => '<code>.uix-typo--h1</code><br>',
    36 => '<code>.uix-typo--h2</code><br>',
    37 => '<code>.uix-typo--h3</code><br>',
    38 => '<code>.uix-typo--h4</code><br>',
    39 => '<code>.uix-typo--h5</code><br>',
    40 => '<code>.uix-typo--h6</code><br>',
    41 => '<code>.uix-typo--style-normal</code><br>',
    42 => '<code>.uix-typo--style-uppercase</code><br>',
    43 => '<code>.uix-typo--style-bold</code><br>',
    44 => '<code>.uix-typo--style-italic</code><br>',
    45 => '<code>.uix-typo--style-noitalic</code><br>',
    46 => '<code>.uix-typo--style-underline</code><br>',
    47 => '<code>.uix-typo--style-tiny</code><br>',
    48 => '<code>.uix-typo--dropcap</code><br>',
    49 => '<code>.uix-typo--vertical</code><br>',
    50 => '<code>.uix-typo--vertical-characters-line</code>',
    51 => '</td>',
    52 => '<td>',
    53 => '<code>.uix-typo--color-primary</code><br>',
    54 => '<code>.uix-typo--color-highlight</code><br>',
    55 => '<code>.uix-typo--color-sub</code><br>',
    56 => '<code>.uix-typo--color-white</code>',
    57 => '</td>',
    58 => '<td>',
    59 => '<code>.uix-display-none</code><br>',
    60 => '<code>.uix-display-inline</code><br>',
    61 => '<code>.uix-display-inline-block</code><br>',
    62 => '<code>.uix-display-block</code><br>',
    63 => '<code>.uix-display-flex</code><br>',
    64 => '<code>.uix-display-inline-flex</code><br>',
    65 => '<strong>The breakpoint is the same as bootstrap 4.</strong><br>',
    66 => '<small>sm(576px)</small> &rArr; <code>.uix-display-none--sm</code>, <code>.uix-display-inline--sm</code>, <code>.uix-display-inline-block--sm</code>, <code>.uix-display-block--sm</code>, <code>.uix-display-flex--sm</code>, <code>.uix-display-inline-flex</code><br>',
    67 => '<small>md(768px)</small> &rArr; <code>.uix-display-none--md</code>, <code>.uix-display-inline--md</code>, <code>.uix-display-inline-block--md</code>, <code>.uix-display-block--md</code>, <code>.uix-display-flex--md</code>, <code>.uix-display-inline-flex</code><br>',
    68 => '<small>lg(992px)</small> &rArr; <code>.uix-display-none--lg</code>, <code>.uix-display-inline--lg</code>, <code>.uix-display-inline-block--lg</code>, <code>.uix-display-block--lg</code>, <code>.uix-display-flex--lg</code>, <code>.uix-display-inline-flex</code><br>',
    69 => '<small>xl(1200px)</small> &rArr; <code>.uix-display-none--xl</code>, <code>.uix-display-inline--xl</code>, <code>.uix-display-inline-block--xl</code>, <code>.uix-display-block--xl</code>, <code>.uix-display-flex--xl</code>, <code>.uix-display-inline-flex</code><br>',
    70 => '</td>',
    71 => '</tr>',
    72 => '</tbody>',
    73 => '</table>',
    74 => '</div>',
    75 => '</div><!-- .table-responsive-md -->',
    76 => '<div class="table-responsive-md">',
    77 => '<div class="uix-table uix-table--bordered">',
    78 => '<table>',
    79 => '<thead>',
    80 => '<tr>',
    81 => '<th>Spacing</th>',
    82 => '<th>Content Block</th>',
    83 => '<th>Clear Element</th>',
    84 => '</tr>',
    85 => '</thead>',
    86 => '<tbody>',
    87 => '<tr>',
    88 => '<td>',
    89 => '<code>.uix-spacing--s</code><br>',
    90 => '<code>.uix-spacing--m</code><br>',
    91 => '<code>.uix-spacing--l</code><br>',
    92 => '<code>.uix-spacing--no-top</code><br>',
    93 => '<code>.uix-spacing--no-bottom</code><br>',
    94 => '<code>.uix-spacing--googlemap</code><br>',
    95 => '<code>.uix-spacing--no</code>',
    96 => '</td>',
    97 => '<td>',
    98 => '<code>.uix-relative</code><br>',
    99 => '<code>.uix-relative--inline</code><br>',
    100 => '<code>.uix-relative--inline-clip</code>',
    101 => '</td>',
    102 => '<td>',
    103 => '<code>.uix-clearfix</code>',
    104 => '</td>',
    105 => '</tr>',
    106 => '</tbody>',
    107 => '</table>',
    108 => '</div>',
    109 => '</div><!-- .table-responsive-md -->',
    110 => '<div class="table-responsive-md">',
    111 => '<div class="uix-table uix-table--bordered">',
    112 => '<table>',
    113 => '<thead>',
    114 => '<tr>',
    115 => '<th>Shadow</th>',
    116 => '<th>Smooth Transition</th>',
    117 => '<th>Element Floating</th>',
    118 => '</tr>',
    119 => '</thead>',
    120 => '<tbody>',
    121 => '<tr>',
    122 => '<td>',
    123 => '<code>.uix-outer-shadow--regular</code><br>',
    124 => '<code>.uix-outer-shadow--thick</code><br>',
    125 => '<code>.uix-outer-shadow--light</code><br>',
    126 => '<code>.uix-outer-shadow--highlight</code><br>',
    127 => '<code>.uix-none-shadow</code>',
    128 => '</td>',
    129 => '<td>',
    130 => '<code>.uix-trans</code>',
    131 => '</td>',
    132 => '<td>',
    133 => '<code>.uix-f-l</code><br>',
    134 => '<code>.uix-f-r</code>',
    135 => '</td>',
    136 => '</tr>',
    137 => '</tbody>',
    138 => '</table>',
    139 => '</div>',
    140 => '</div><!-- .table-responsive-md -->',
    141 => '<div class="table-responsive-md">',
    142 => '<div class="uix-table uix-table--bordered">',
    143 => '<table>',
    144 => '<thead>',
    145 => '<tr>',
    146 => '<th>Element Alignment</th>',
    147 => '<th>Truncate String with Ellipsis</th>',
    148 => '<th>Vertically or Horizontally Aligned Blocks</th>',
    149 => '</tr>',
    150 => '</thead>',
    151 => '<tbody>',
    152 => '<tr>',
    153 => '<td>',
    154 => '<code>.uix-t-r</code><br>',
    155 => '<code>.uix-t-l</code><br>',
    156 => '<code>.uix-t-c</code><br>',
    157 => '<strong>The breakpoint is the same as bootstrap 4.</strong><br>',
    158 => '<small>sm(576px)</small> &rArr; <code>.uix-t-r--sm</code>, <code>.uix-t-l--sm</code>, <code>.uix-t-c--sm</code><br>',
    159 => '<small>md(768px)</small> &rArr; <code>.uix-t-r--md</code>, <code>.uix-t-l--md</code>, <code>.uix-t-c--md</code><br>',
    160 => '<small>lg(992px)</small> &rArr; <code>.uix-t-r--lg</code>, <code>.uix-t-l--lg</code>, <code>.uix-t-c--lg</code><br>',
    161 => '<small>xl(1200px)</small> &rArr; <code>.uix-t-r--xl</code>, <code>.uix-t-l--xl</code>, <code>.uix-t-c--xl</code><br>',
    162 => '</td>',
    163 => '<td>',
    164 => '<code>.uix-t-ellipsis</code>',
    165 => '</td>',
    166 => '<td>',
    167 => '<code>.uix-v-align--absolute</code><br>',
    168 => '<code>.uix-v-align--absolute.uix-v-align--absolute--b</code>',
    169 => '<div class="uix-tooltip">',
    170 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    171 => '<div class="uix-t-l">Align content of a div to the bottom</div>',
    172 => '</div>',
    173 => '<br>',
    174 => '<code>.uix-v-align--absolute.uix-v-align--absolute--t</code>',
    175 => '<div class="uix-tooltip">',
    176 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    177 => '<div class="uix-t-l">Align content of a div to the top</div>',
    178 => '</div>',
    179 => '<br>',
    180 => '<code>.uix-v-align--relative</code><br>',
    181 => '<code>.uix-v-align--table</code><br>',
    182 => '<code>.uix-v-align--table.uix-v-align--table--b</code>',
    183 => '<div class="uix-tooltip">',
    184 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    185 => '<div class="uix-t-l">Align content of a div to the bottom</div>',
    186 => '</div>',
    187 => '<br>',
    188 => '<code>.uix-v-align--table.uix-v-align--table--t</code>',
    189 => '<div class="uix-tooltip">',
    190 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    191 => '<div class="uix-t-l">Align content of a div to the top</div>',
    192 => '</div>',
    193 => '<br>',
    194 => '</td>',
    195 => '</tr>',
    196 => '</tbody>',
    197 => '</table>',
    198 => '</div>',
    199 => '</div><!-- .table-responsive-md -->',
    200 => '<div class="table-responsive-md">',
    201 => '<div class="uix-table uix-table--bordered">',
    202 => '<table>',
    203 => '<thead>',
    204 => '<tr>',
    205 => '<th>Specifies Whether To Clip Content</th>',
    206 => '<th>Specifies a Default Height <span class="uix-typo--style-normal uix-typo--color-sub">(unit: vh)</span>.</th>',
    207 => '<th>Hidden Element on Mobile/Desktop</th>',
    208 => '</tr>',
    209 => '</thead>',
    210 => '<tbody>',
    211 => '<tr>',
    212 => '<td>',
    213 => '<code>.uix-hidden-scrollbar-x</code><br>',
    214 => '<code>.uix-hidden-scrollbar</code>',
    215 => '</td>',
    216 => '<td>',
    217 => '<code>.uix-height--10</code><br>',
    218 => '<code>.uix-height--20</code><br>',
    219 => '<code>.uix-height--30</code><br>',
    220 => '<code>.uix-height--40</code><br>',
    221 => '<code>.uix-height--50</code><br>',
    222 => '<code>.uix-height--60</code><br>',
    223 => '<code>.uix-height--70</code><br>',
    224 => '<code>.uix-height--80</code><br>',
    225 => '<code>.uix-height--90</code><br>',
    226 => '<code>.uix-height--100</code><br>',
    227 => '<p class="uix-striking-msg uix-striking-msg--info is-rounded">',
    228 => 'Keep the same height as the PC on mobile devices, it can be used with <code>.is-mobile-still</code>',
    229 => '</p>',
    230 => '</td>',
    231 => '<td>',
    232 => '<code>.uix-hide-mobile</code>',
    233 => '<div class="uix-tooltip">',
    234 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    235 => '<div class="uix-t-l">Only display element on desktop devices.</div>',
    236 => '</div>',
    237 => '<br>',
    238 => '<code>.uix-hide-pc</code>',
    239 => '<div class="uix-tooltip">',
    240 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    241 => '<div class="uix-t-l">Only display element on mobile devices.</div>',
    242 => '</div>',
    243 => '<br>',
    244 => '</td>',
    245 => '</tr>',
    246 => '</tbody>',
    247 => '</table>',
    248 => '</div>',
    249 => '</div><!-- .table-responsive-md -->',
    250 => '<div class="table-responsive-md">',
    251 => '<div class="uix-table uix-table--bordered">',
    252 => '<table>',
    253 => '<thead>',
    254 => '<tr>',
    255 => '<th>Tip Bubble</th>',
    256 => '<th>Image Hover Overlay Effects</th>',
    257 => '<th>Position</th>',
    258 => '</tr>',
    259 => '</thead>',
    260 => '<tbody>',
    261 => '<tr>',
    262 => '<td>',
    263 => '<code>.uix-bubble</code>',
    264 => '</td>',
    265 => '<td>',
    266 => '<code>.uix-filter-hover--color</code>',
    267 => '</td>',
    268 => '<td>',
    269 => '<code>.uix-dir--top</code><br>',
    270 => '<code>.uix-dir--bottom</code><br>',
    271 => '<code>.uix-dir--left</code><br>',
    272 => '<code>.uix-dir--right</code><br>',
    273 => '<code>.uix-dir--top-left</code><br>',
    274 => '<code>.uix-dir--top-right</code><br>',
    275 => '<code>.uix-dir--bottom-left</code><br>',
    276 => '<code>.uix-dir--bottom-right</code>',
    277 => '</td>',
    278 => '</tr>',
    279 => '</tbody>',
    280 => '</table>',
    281 => '</div>',
    282 => '</div><!-- .table-responsive-md -->',
    283 => '<div class="table-responsive-md">',
    284 => '<div class="uix-table uix-table--bordered">',
    285 => '<table>',
    286 => '<thead>',
    287 => '<tr>',
    288 => '<th>Element Hidden Style</th>',
    289 => '<th>Border Radius</th>',
    290 => '<th>Align Wide and Full Classes For Elements</th>',
    291 => '</tr>',
    292 => '</thead>',
    293 => '<tbody>',
    294 => '<tr>',
    295 => '<td>',
    296 => '<code>.uix-el--transparent</code>',
    297 => '<div class="uix-tooltip">',
    298 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    299 => '<div class="uix-t-l">Set the transparency of the element to 0.</div>',
    300 => '</div>',
    301 => '<br>',
    302 => '<code>.uix-el--scale</code>',
    303 => '<div class="uix-tooltip">',
    304 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    305 => '<div class="uix-t-l">Set the scale of the element to 0.</div>',
    306 => '</div>',
    307 => '<br>',
    308 => '<code>.uix-el--skew</code>',
    309 => '<div class="uix-tooltip">',
    310 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    311 => '<div class="uix-t-l">Tilt the element a certain degree to the upper right.</div>',
    312 => '</div>',
    313 => '</td>',
    314 => '<td>',
    315 => '<code>.uix-border--rounded</code><br>',
    316 => '<code>.uix-border--circle</code><br>',
    317 => '<code>.uix-border--circle.uix-border--circle-img</code>',
    318 => '<div class="uix-tooltip">',
    319 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    320 => '<div class="uix-t-l">Make a circle image with <code>&lt;img&gt;</code></div>',
    321 => '</div>',
    322 => '<br>',
    323 => '<code>.uix-border--circle.uix-border--circle-only-img</code>',
    324 => '<div class="uix-tooltip">',
    325 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    326 => '<div class="uix-t-l">Make a circle image with <code>&lt;img&gt;</code> only.</div>',
    327 => '</div>',
    328 => '<br>',
    329 => '<code>.uix-border--rounded.uix-border--rounded-img</code>',
    330 => '<div class="uix-tooltip">',
    331 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    332 => '<div class="uix-t-l">Make a rounded image with <code>&lt;img&gt;</code></div>',
    333 => '</div>',
    334 => '<br>',
    335 => '<code>.uix-border--rounded.uix-border--rounded-only-img</code>',
    336 => '<div class="uix-tooltip">',
    337 => '<span data-microtip-position="top" data-microtip-size="large" role="tooltip"><i class="fa fa-question-circle uix-typo--color-sub" aria-hidden="true"></i></span>',
    338 => '<div class="uix-t-l">Make a rounded image with <code>&lt;img&gt;</code> only.</div>',
    339 => '</div>',
    340 => '</td>',
    341 => '<td>',
    342 => '<code>.uix-alignfull</code>',
    343 => '</td>',
    344 => '</tr>',
    345 => '</tbody>',
    346 => '</table>',
    347 => '</div>',
    348 => '</div><!-- .table-responsive-md -->',
    349 => '</div>',
    350 => '</div>',
    351 => '<!-- .row end -->',
    352 => '</div>',
    353 => '<!-- .container end -->',
    354 => '</section>',
    355 => '</main>',
  ),
  'footer' => 
  array (
    0 => '<footer class="uix-footer__container">',
    1 => '<div class="uix-footer">',
    2 => '<div class="container">',
    3 => '<hr>',
    4 => '<div class="row">',
    5 => '<div class="col-lg-6 col-md-6 uix-t-l uix-t-c--md">',
    6 => 'Copyright &copy; Uix Kit 2019.  |  All rights reserved. Created by <a href="https://uiux.cc">UIUX Lab</a>.',
    7 => '</div>',
    8 => '<div class="col-lg-6 col-md-6 uix-t-r uix-t-c--md">',
    9 => '<div class="uix-footer__menu">',
    10 => '<ul>',
    11 => '<li>',
    12 => '<a href="https://uiux.cc" target="_blank">',
    13 => 'UIUX Lab',
    14 => '</a>',
    15 => '</li>',
    16 => '<li>',
    17 => '<a href="https://opensource.org/licenses/MIT" target="_blank">',
    18 => 'Licenses',
    19 => '</a>',
    20 => '</li>',
    21 => '<li>',
    22 => '<a href="https://github.com/xizon/uix-kit" target="_blank">',
    23 => 'Download',
    24 => '</a>',
    25 => '</li>',
    26 => '<li>',
    27 => '<a href="https://github.com/xizon/uix-kit/wiki/Getting-Started" target="_blank">',
    28 => 'Documentation',
    29 => '</a>',
    30 => '</li>',
    31 => '</ul>',
    32 => '</div>',
    33 => '</div>',
    34 => '</div>',
    35 => '</div><!-- .container  end -->',
    36 => '</div>',
    37 => '</footer>',
  ),
  'bottom' => 
  array (
    0 => '<!-- Vendor -->',
    1 => '<script defer src="../assets/js/min/axios.min.js?ver=0.19.2"></script>',
    2 => '<script defer src="../assets/js/min/jquery.waitforimages.min.js?ver=1.0"></script>',
    3 => '<script defer src="../assets/js/min/video.min.js?ver=7.5.3"></script>',
    4 => '<script defer src="../assets/js/min/template7.min.js?ver=1.4.2"></script>',
    5 => '<script defer src="../assets/js/min/TweenMax.min.js?ver=2.0.2"></script>',
    6 => '<script defer src="../assets/js/min/pixi.min.js?ver=5.2.0"></script>',
    7 => '<script defer src="../assets/js/min/three.min.js?ver=r114"></script>',
    8 => '<script defer src="../assets/js/min/anime.min.js?ver=3.1"></script>',
    9 => '<script defer src="../assets/js/min/hammer.min.js?ver=2.0.8"></script>',
    10 => '<script defer src="../assets/js/min/muuri.min.js?ver=0.8.0"></script>',
    11 => '<!-- Your Plugins & Theme Scripts',
    12 => '============================================= -->',
    13 => '<script>',
    14 => '/*',
    15 => '* Some global vars. DO NOT change these variables names.',
    16 => '* These variables are being used in `uix-kit.min.js`.',
    17 => '*',
    18 => '*/',
    19 => 'var REVISION     = "4.6.5",',
    20 => 'APP_ROOTPATH = {',
    21 => '"templateUrl" : "", //If the file is in the root directory, you can leave it empty. If in another directory, you can write: "/blog"',
    22 => '"homeUrl"     : "",  //Eg. https://uiux.cc',
    23 => '"ajaxUrl"     : ""   //Eg. https://uiux.cc/wp-admin/admin-ajax.php',
    24 => '};',
    25 => '/*',
    26 => '* Fixed a bug that Cannot read property \'fn\' of undefined for jQuery 1.xx.x.',
    27 => '*',
    28 => '*/',
    29 => 'window.$ = window.jQuery;',
    30 => '</script>',
    31 => '<script defer src=../js/uix-kit.min.js?ver=qXJ1d1suw95dRqLHFWpI"></script>',
    32 => '<!-- Your Plugins & Theme Scripts  end -->',
    33 => '<script>',
    34 => '/* Google analytics */',
    35 => '(function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){',
    36 => '(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),',
    37 => 'm=s.getElementsByTagName(o)[0];a.defer=1;a.src=g;m.parentNode.insertBefore(a,m)',
    38 => '})(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');',
    39 => 'ga(\'create\', \'UA-70658525-1\', \'auto\');',
    40 => 'ga(\'send\', \'pageview\');',
    41 => '</script>',
    42 => '</body>',
    43 => '</html>',
  ),
);
