INSERT INTO `wp_page0104` (`id`, `name`, `site_code`, `code`, `url`, `is_mobile`, `status`) VALUES 
(NULL, '美国总统', 'graphic', 'president', 'http://114.xixik.com/potus/', '0', '0'),
(NULL, '朝代', 'graphic', 'dynasty', 'http://114.xixik.com/chaodai/', '0', '0'),
(NULL, '皇帝', 'graphic', 'emperor', 'http://114.xixik.com/chinese-emperors/qing/', '0', '0'),

(NULL, '美国总统', 'graphic', 'president', 'http://m.114.xixik.com/potus/', '1', '0'),
(NULL, '朝代', 'graphic', 'dynasty', 'http://m.114.xixik.com/chaodai/', '1', '0'),
(NULL, '皇帝', 'graphic', 'emperor', 'http://m.114.xixik.com/chinese-emperors/qing/', '1', '0'),


(NULL, '排行榜', 'nav', 'rank', 'http://guozhivip.com/rank/', '0', '0'),
(NULL, '运营', 'nav', 'operation', 'http://guozhivip.com/pod/', '0', '0'),
(NULL, '工具', 'nav', 'tool', 'http://guozhivip.com/tool/', '0', '0'),
(NULL, '搜索', 'nav', 'search', 'http://guozhivip.com/so/', '0', '0'),
(NULL, '酷站', 'nav', 'coolsite', 'http://guozhivip.com/lab/', '0', '0'),
(NULL, '设计', 'nav', 'design', 'http://guozhivip.com/design/', '0', '0'),
(NULL, '导航', 'nav', 'nav', 'http://guozhivip.com/', '0', '0'),
(NULL, '阅读', 'nav', 'readnav', 'http://guozhivip.com/xs/', '0', '0'),
(NULL, '购物', 'nav', 'shop', 'http://guozhivip.com/hg/', '0', '0'),
(NULL, '新闻', 'nav', 'news', 'http://guozhivip.com/news/', '0', '0'),
(NULL, '影视', 'nav', 'tvfilm', 'http://guozhivip.com/mvs.html', '0', '0'),
(NULL, '游戏', 'nav', 'game', 'http://guozhivip.com/game/', '0', '0'),
(NULL, '图片', 'nav', 'picture', 'http://guozhivip.com/imgs.html', '0', '0'),
(NULL, '学习', 'nav', 'study', 'http://guozhivip.com/edu/', '0', '0'),
(NULL, '动漫', 'nav', 'cartoon', 'http://guozhivip.com/mh/', '0', '0'),
(NULL, '', 'nav', '', '', '0', '0'),

(NULL, '首页', 'kongfz', 'home', 'https://m.kongfz.com/', '1', '0'),
(NULL, '书店', 'kongfz', 'store', 'https://m.kongfz.com/channel/1081', '1', '0'),
(NULL, '分类', 'kongfz', 'category', 'https://m.kongfz.com/category/', '1', '0'),
(NULL, '图书首页', 'kongfz', 'bookhome', 'https://mbook.kongfz.com/', '1', '0'),
(NULL, '图书列表', 'kongfz', 'booklist', 'http://mbook.kongfz.com/Cminguo/', '1', '0'),
(NULL, '图书详情', 'kongfz', 'bookdetail', 'https://mbook.kongfz.com/12820/4038675393/', '1', '0'),
(NULL, '人物详情', 'kongfz', 'figure', 'http://promotion.kongfz.com/promotion/Borges_m', '1', '0'),
(NULL, '人物详情2', 'kongfz', 'figure2', 'http://promotion.kongfz.com/promotion/qianmu_m', '1', '0'),
(NULL, '频道', 'kongfz', 'channel', 'https://m.kongfz.com/channel/1097', '1', '0'),
(NULL, '书单', 'kongfz', 'shelf', 'https://m.kongfz.com/booklist/', '1', '0'),
(NULL, '专辑', 'kongfz', 'collection', 'http://promotion.kongfz.com/promotion/mmyg_m', '1', '0'),
(NULL, '', 'kongfz', '', '', '1', '0'),







(NULL, '首页', 'culture', 'home', 'http://www.yac8.com/', '0', '0'),
(NULL, '列表页', 'culture', 'list', 'http://www.yac8.com/news/list_5.html', '0', '0'),
(NULL, '详情页', 'culture', 'show', 'http://www.yac8.com/news/15659.html', '0', '0'),

(NULL, '首页', 'culture', 'home', 'http://m.yac8.com/', '1', '0'),
(NULL, '列表页', 'culture', 'list', 'http://m.yac8.com/news/list_5.html', '1', '0'),
(NULL, '详情页', 'culture', 'show', 'http://m.yac8.com/news/15659.html', '1', '0'),


(NULL, '首页', 'petinfo', 'home', 'https://www.petquan.cn/', '0', '0'),
(NULL, '宠物种类', 'petinfo', 'list-sort', 'https://www.petquan.cn/daquan/', '0', '0'),
(NULL, '种类详情', 'petinfo', 'show-sort', 'https://www.petquan.cn/guibin/', '0', '0'),
(NULL, '宠物视频', 'petinfo', 'list-video', 'https://www.petquan.cn/video/', '0', '0'),
(NULL, '视频详情', 'petinfo', 'show-video', 'https://www.petquan.cn/maomidaquan/34372.html', '0', '0'),
(NULL, '宠物资讯', 'petinfo', 'list-info', 'https://www.petquan.cn/news/', '0', '0'),
(NULL, '资讯详情', 'petinfo', 'show-info', 'https://www.petquan.cn/news/29910.html', '0', '0'),

(NULL, '首页', 'petinfo', 'home', 'https://mip.petquan.cn/', '1', '0'),
(NULL, '宠物种类', 'petinfo', 'list-sort', 'https://mip.petquan.cn/daquan/', '1', '0'),
(NULL, '种类详情', 'petinfo', 'show-sort', 'https://mip.petquan.cn/guibin/', '1', '0'),
(NULL, '宠物视频', 'petinfo', 'list-video', 'https://mip.petquan.cn/video/', '1', '0'),
(NULL, '视频详情', 'petinfo', 'show-video', 'https://mip.petquan.cn/maomidaquan/34372.html', '1', '0'),
(NULL, '宠物资讯', 'petinfo', 'list-info', 'https://mip.petquan.cn/news/', '1', '0'),
(NULL, '资讯详情', 'petinfo', 'show-video', 'https://mip.petquan.cn/news/29910.html', '1', '0'),

(NULL, '首页', 'sguide', 'home', 'https://www.maigoo.com/maigoo/151wj_index.html', '0', '0'),
(NULL, '知识', 'sguide', 'knowledge', 'https://www.maigoo.com/goomai/list_797.html', '0', '0'),
(NULL, '网店', 'sguide', 'shop', 'https://www.maigoo.com/webshop/list_797.html', '0', '0'),
(NULL, '产品', 'sguide', 'product', 'https://www.maigoo.com/product/list_797.html', '0', '0'),
(NULL, '加盟', 'sguide', 'league', 'https://www.maigoo.com/zhaoshang/list_797.html', '0', '0'),
(NULL, '聚焦', 'sguide', 'info', 'https://www.maigoo.com/news/list_797.html', '0', '0'),
(NULL, '名人', 'sguide', 'human', 'https://www.maigoo.com/mingren/list_797.html', '0', '0'),
(NULL, '网点', 'sguide', 'store', 'https://www.maigoo.com/shop/list_797.html', '0', '0'),
(NULL, '投票', 'sguide', 'vote', 'https://www.maigoo.com/vote/list_797.html', '0', '0'),
(NULL, '网点详情', 'sguide', 'show-store', 'https://www.maigoo.com/shop/314165.html', '0', '0'),
(NULL, '名人详情', 'sguide', 'show-human', 'https://www.maigoo.com/mingren/8452.html', '0', '0'),
(NULL, '聚焦详情', 'sguide', 'show-info', 'https://www.maigoo.com/news/578663.html', '0', '0'),
(NULL, '加盟详情', 'sguide', 'show-league', 'https://www.maigoo.com/zhaoshang/862.html', '0', '0'),
(NULL, '网点详情', 'sguide', 'show-shop', 'https://www.maigoo.com/webshop/155559.html', '0', '0'),
(NULL, '知识详情', 'sguide', 'show-knowledge', 'https://www.maigoo.com/best/8331.html', '0', '0'),
(NULL, '品牌首页', 'sguide', 'brand', 'https://www.maigoo.com/maigoocms/special/qinzi/154chenguang.html', '0', '0'),
(NULL, '品牌产品', 'sguide', 'brand-product', 'https://www.maigoo.com/brand/product_2411.html', '0', '0'),
(NULL, '品牌网店', 'sguide', 'brand-shop', 'https://www.maigoo.com/brand/webshop_2411.html', '0', '0'),
(NULL, '品牌网点', 'sguide', 'brand-store', 'https://www.maigoo.com/brand/shop_2411.html', '0', '0'),
(NULL, '品牌详情', 'sguide', 'brand-detail', 'https://www.maigoo.com/company/2411.html?brandid=2411', '0', '0'),

(NULL, '首页', 'sguide', 'home', 'https://m.maigoo.com/maigoo/151wj_index.html', '1', '0'),
(NULL, '知识', 'sguide', 'knowledge', 'https://m.maigoo.com/goomai/list_797.html', '1', '0'),
(NULL, '网店', 'sguide', 'shop', 'https://m.maigoo.com/webshop/list_797.html', '1', '0'),
(NULL, '产品', 'sguide', 'product', 'https://m.maigoo.com/product/list_797.html', '1', '0'),
(NULL, '加盟', 'sguide', 'league', 'https://m.maigoo.com/zhaoshang/list_797.html', '1', '0'),
(NULL, '聚焦', 'sguide', 'info', 'https://m.maigoo.com/news/list_797.html', '1', '0'),
(NULL, '名人', 'sguide', 'human', 'https://m.maigoo.com/mingren/list_797.html', '1', '0'),
(NULL, '网点', 'sguide', 'store', 'https://m.maigoo.com/shop/list_797.html', '1', '0'),
(NULL, '投票', 'sguide', 'vote', 'https://m.maigoo.com/vote/list_797.html', '1', '0'),
(NULL, '网点详情', 'sguide', 'show-store', 'https://m.maigoo.com/shop/314165.html', '1', '0'),
(NULL, '名人详情', 'sguide', 'show-human', 'https://m.maigoo.com/mingren/8452.html', '1', '0'),
(NULL, '聚焦详情', 'sguide', 'show-info', 'https://m.maigoo.com/news/578663.html', '1', '0'),
(NULL, '加盟详情', 'sguide', 'show-league', 'https://m.maigoo.com/zhaoshang/862.html', '1', '0'),
(NULL, '网点详情', 'sguide', 'show-shop', 'https://m.maigoo.com/webshop/155559.html', '1', '0'),
(NULL, '知识详情', 'sguide', 'show-knowledge', 'https://m.maigoo.com/best/8331.html', '1', '0'),
(NULL, '品牌首页', 'sguide', 'brand', 'https://m.maigoo.com/maigoocms/special/qinzi/154chenguang.html', '1', '0'),
(NULL, '品牌产品', 'sguide', 'brand-product', 'https://m.maigoo.com/brand/product_2411.html', '1', '0'),
(NULL, '品牌网店', 'sguide', 'brand-shop', 'https://m.maigoo.com/brand/webshop_2411.html', '1', '0'),
(NULL, '品牌网点', 'sguide', 'brand-store', 'https://m.maigoo.com/brand/shop_2411.html', '1', '0'),
(NULL, '品牌详情', 'sguide', 'brand-detail', 'https://m.maigoo.com/company/2411.html?brandid=2411', '1', '0'),

(NULL, '', 'petinfo', '', '', '1', '0'),
(NULL, '', 'petinfo', '', '', '1', '0'),
(NULL, '', 'petinfo', '', '', '1', '0'),

(NULL, '', 'yac8', '', '', '0', '0'),
(NULL, '', 'yac8', '', '', '1', '0'),

(NULL, '', '', '', '', '0', '0'),
(NULL, '', '', '', '', '1', '0'),
